<?php

return [
    'modules' => [
        'customers' => [
            'title' => 'Quản Lý Khách Hàng',
            'singular' => 'khách hàng',
            'description' => 'Danh sách khách hàng đang lưu trữ trong hệ thống khách sạn.',
            'primary_key' => 'MaKH',
            'list_columns' => ['MaKH', 'MaTK', 'TenKH', 'DiaChi', 'SoDienThoai', 'CCCD', 'NgaySinh', 'GioiTinh', 'Diem', 'TrangThai'],
            'fields' => [
                'MaKH' => ['label' => 'Mã khách hàng', 'type' => 'number', 'readonly' => true],
                'MaTK' => ['label' => 'Mã tài khoản', 'type' => 'number', 'required' => true],
                'TenKH' => ['label' => 'Tên khách hàng', 'type' => 'text', 'required' => true],
                'DiaChi' => ['label' => 'Địa chỉ', 'type' => 'textarea', 'required' => true],
                'SoDienThoai' => ['label' => 'Số điện thoại', 'type' => 'text', 'required' => true],
                'CCCD' => ['label' => 'CCCD', 'type' => 'text', 'required' => true],
                'NgaySinh' => ['label' => 'Ngày sinh', 'type' => 'date', 'required' => true],
                'GioiTinh' => ['label' => 'Giới tính', 'type' => 'select', 'options' => [0 => 'Nữ', 1 => 'Nam', 2 => 'Khác']],
                'Diem' => ['label' => 'Điểm tích lũy', 'type' => 'number'],
                'TrangThai' => ['label' => 'Trạng thái', 'type' => 'select', 'options' => [0 => 'Không hoạt động', 1 => 'Hoạt động']],
            ],
            'records' => [
                ['MaKH' => 1, 'MaTK' => 101, 'TenKH' => 'Nguyễn Minh An', 'DiaChi' => '12 Nguyễn Huệ, Quận 1, TP.HCM', 'SoDienThoai' => '0901234567', 'CCCD' => '079204000111', 'NgaySinh' => '1998-04-12', 'GioiTinh' => 1, 'Diem' => 120, 'TrangThai' => 1],
                ['MaKH' => 2, 'MaTK' => 102, 'TenKH' => 'Trần Bảo Ngọc', 'DiaChi' => '55 Lê Lợi, Hải Châu, Đà Nẵng', 'SoDienThoai' => '0912345678', 'CCCD' => '048204000222', 'NgaySinh' => '2000-08-24', 'GioiTinh' => 0, 'Diem' => 80, 'TrangThai' => 1],
                ['MaKH' => 3, 'MaTK' => 103, 'TenKH' => 'Lê Quốc Huy', 'DiaChi' => '99 Hai Bà Trưng, Ninh Kiều, Cần Thơ', 'SoDienThoai' => '0987654321', 'CCCD' => '079204000333', 'NgaySinh' => '1995-11-03', 'GioiTinh' => 1, 'Diem' => 35, 'TrangThai' => 0],
            ],
        ],
        'accounts' => [
            'title' => 'Quản Lý Tài Khoản',
            'singular' => 'tài khoản',
            'description' => 'Quản lý thông tin đăng nhập, phân loại tài khoản và trạng thái sử dụng.',
            'primary_key' => 'MaTK',
            'list_columns' => ['MaTK', 'Email', 'LoaiTaiKhoan', 'TrangThai'],
            'fields' => [
                'MaTK' => ['label' => 'Mã tài khoản', 'type' => 'number', 'readonly' => true],
                'Email' => ['label' => 'Email', 'type' => 'email', 'required' => true],
                'MatKhau' => ['label' => 'Mật khẩu', 'type' => 'password', 'required' => true],
                'LoaiTaiKhoan' => ['label' => 'Loại tài khoản', 'type' => 'select', 'options' => [0 => 'Khách hàng', 1 => 'Nhân viên', 2 => 'Quản lý']],
                'TrangThai' => ['label' => 'Trạng thái', 'type' => 'select', 'options' => [0 => 'Không hoạt động', 1 => 'Hoạt động']],
            ],
            'records' => [
                ['MaTK' => 101, 'Email' => 'minhan@gmail.com', 'MatKhau' => '••••••••', 'LoaiTaiKhoan' => 0, 'TrangThai' => 1],
                ['MaTK' => 201, 'Email' => 'letan01@peachvalley.vn', 'MatKhau' => '••••••••', 'LoaiTaiKhoan' => 1, 'TrangThai' => 1],
                ['MaTK' => 301, 'Email' => 'admin@peachvalley.vn', 'MatKhau' => '••••••••', 'LoaiTaiKhoan' => 2, 'TrangThai' => 1],
            ],
        ],
        'employees' => [
            'title' => 'Quản Lý Nhân Viên',
            'singular' => 'nhân viên',
            'description' => 'Danh sách quản lý thông tin nhân viên.',
            'primary_key' => 'MaNV',
            'list_columns' => ['MaNV', 'TenNV', 'MaTK'],
            'fields' => [
                'MaNV' => ['label' => 'Mã nhân viên', 'type' => 'number', 'readonly' => true],
                'TenNV' => ['label' => 'Tên nhân viên', 'type' => 'text', 'required' => true],
                'MaTK' => ['label' => 'Mã tài khoản', 'type' => 'number', 'required' => true],
            ],
            'records' => [
                ['MaNV' => 1, 'TenNV' => 'Phạm Thùy Linh', 'MaTK' => 201],
                ['MaNV' => 2, 'TenNV' => 'Hoàng Gia Bảo', 'MaTK' => 202],
                ['MaNV' => 3, 'TenNV' => 'Đặng Tuấn Kiệt', 'MaTK' => 203],
            ],
        ],
        'rooms' => [
            'title' => 'Quản Lý Phòng',
            'singular' => 'phòng',
            'description' => 'Danh sách quản lý thông tin các phòng tại khách sạn.',
            'primary_key' => 'MaPhong',
            'list_columns' => ['MaPhong', 'SoPhong', 'TenLoaiPhong', 'MaLoaiPhong', 'TinhTrang'],
            'fields' => [
                'MaPhong' => ['label' => 'Mã phòng', 'type' => 'number', 'readonly' => true],
                'SoPhong' => ['label' => 'Số phòng', 'type' => 'text', 'required' => true],
                'MaLoaiPhong' => ['label' => 'Mã loại phòng', 'type' => 'number', 'required' => true],
                'TenLoaiPhong' => ['label' => 'Tên loại phòng', 'type' => 'text'],
                'TinhTrang' => ['label' => 'Tình trạng', 'type' => 'select', 'options' => [0 => 'Trống', 1 => 'Đã đặt', 2 => 'Đang sử dụng', 3 => 'Đang dọn dẹp']],
            ],
            'records' => [
                ['MaPhong' => 1, 'SoPhong' => 'A101', 'MaLoaiPhong' => 1, 'TenLoaiPhong' => 'Deluxe', 'TinhTrang' => 0],
                ['MaPhong' => 2, 'SoPhong' => 'A102', 'MaLoaiPhong' => 2, 'TenLoaiPhong' => 'Suite', 'TinhTrang' => 2],
                ['MaPhong' => 3, 'SoPhong' => 'B201', 'MaLoaiPhong' => 1, 'TenLoaiPhong' => 'Deluxe', 'TinhTrang' => 3],
            ],
        ],
        'services' => [
            'title' => 'Quản Lý Dịch Vụ',
            'singular' => 'dịch vụ',
            'description' => 'Danh sách quản lý dịch vụ khách sạn cung cấp.',
            'primary_key' => 'MaDV',
            'list_columns' => ['MaDV', 'TenDV', 'GiaDV', 'LoaiDV'],
            'fields' => [
                'MaDV' => ['label' => 'Mã dịch vụ', 'type' => 'number', 'readonly' => true],
                'TenDV' => ['label' => 'Tên dịch vụ', 'type' => 'text', 'required' => true],
                'GiaDV' => ['label' => 'Giá dịch vụ', 'type' => 'number', 'step' => '0.01', 'required' => true],
                'LoaiDV' => ['label' => 'Loại dịch vụ', 'type' => 'select', 'options' => [0 => 'Ăn uống', 1 => 'Giặt ủi', 2 => 'Vệ sinh', 3 => 'Spa', 4 => 'Cưỡi ngựa', 5 => 'Golf', 6 => 'Gym', 7 => 'Đổi phòng', 8 => 'Hủy phòng', 9 => 'Thêm giường phụ']],
            ],
            'records' => [
                ['MaDV' => 1, 'TenDV' => 'Bữa sáng tại phòng', 'GiaDV' => 250000, 'LoaiDV' => 0],
                ['MaDV' => 2, 'TenDV' => 'Giặt ủi nhanh', 'GiaDV' => 120000, 'LoaiDV' => 1],
                ['MaDV' => 3, 'TenDV' => 'Gói spa thư giãn', 'GiaDV' => 850000, 'LoaiDV' => 3],
                ['MaDV' => 4, 'TenDV' => 'Dọn phòng theo yêu cầu', 'GiaDV' => 90000, 'LoaiDV' => 2],
                ['MaDV' => 5, 'TenDV' => 'Trải nghiệm cưỡi ngựa', 'GiaDV' => 650000, 'LoaiDV' => 4],
                ['MaDV' => 6, 'TenDV' => 'Gói chơi golf cuối tuần', 'GiaDV' => 1250000, 'LoaiDV' => 5],
                ['MaDV' => 7, 'TenDV' => 'Thẻ phòng gym 1 ngày', 'GiaDV' => 180000, 'LoaiDV' => 6],
                ['MaDV' => 8, 'TenDV' => 'Hỗ trợ đổi phòng', 'GiaDV' => 150000, 'LoaiDV' => 7],
                ['MaDV' => 9, 'TenDV' => 'Phí hủy phòng linh hoạt', 'GiaDV' => 300000, 'LoaiDV' => 8],
                ['MaDV' => 10, 'TenDV' => 'Thêm giường phụ', 'GiaDV' => 220000, 'LoaiDV' => 9],
            ],
        ],
        'promotions' => [
            'title' => 'Quản Lý Khuyến Mãi',
            'singular' => 'khuyến mãi',
            'description' => 'Danh sách quản lý theo dõi chương trình ưu đãi từ khách sạn.',
            'primary_key' => 'MaKM',
            'list_columns' => ['MaKM', 'TenKM', 'Diem', 'NgayBatDau', 'NgayKetThuc', 'PhanTramGiamGia'],
            'fields' => [
                'MaKM' => ['label' => 'Mã khuyến mãi', 'type' => 'number', 'readonly' => true],
                'TenKM' => ['label' => 'Tên chương trình', 'type' => 'text', 'required' => true],
                'MoTa' => ['label' => 'Mô tả', 'type' => 'textarea', 'required' => true],
                'Diem' => ['label' => 'Điểm yêu cầu', 'type' => 'number'],
                'NgayBatDau' => ['label' => 'Ngày bắt đầu', 'type' => 'date', 'required' => true],
                'NgayKetThuc' => ['label' => 'Ngày kết thúc', 'type' => 'date', 'required' => true],
                'PhanTramGiamGia' => ['label' => 'Phần trăm giảm giá', 'type' => 'number', 'step' => '0.01', 'required' => true],
            ],
            'records' => [
                ['MaKM' => 1, 'TenKM' => 'Summer Escape', 'MoTa' => 'Giảm giá cho khách đặt phòng trong mùa hè.', 'Diem' => 50, 'NgayBatDau' => '2026-05-01', 'NgayKetThuc' => '2026-06-30', 'PhanTramGiamGia' => 15],
                ['MaKM' => 2, 'TenKM' => 'Stay Longer', 'MoTa' => 'Ưu đãi dành cho khách ở từ 3 đêm trở lên.', 'Diem' => 80, 'NgayBatDau' => '2026-04-15', 'NgayKetThuc' => '2026-07-31', 'PhanTramGiamGia' => 20],
            ],
        ],
        'payments' => [
            'title' => 'Quản Lý Thanh Toán',
            'singular' => 'thanh toán',
            'description' => 'Quản lý thông tin thanh toán, hóa đơn.',
            'primary_key' => 'MaTT',
            'list_columns' => ['MaTT', 'MaHD', 'SoTien', 'PhuongThuc', 'LoaiThanhToan', 'NgayThanhToan', 'TrangThaiHoaDon'],
            'fields' => [
                'MaTT' => ['label' => 'Mã thanh toán', 'type' => 'number', 'readonly' => true],
                'MaHD' => ['label' => 'Mã hóa đơn', 'type' => 'number', 'required' => true],
                'SoTien' => ['label' => 'Số tiền', 'type' => 'number', 'step' => '0.01', 'required' => true],
                'PhuongThuc' => ['label' => 'Phương thức', 'type' => 'select', 'options' => [1 => 'Thẻ', 2 => 'QRCode']],
                'LoaiThanhToan' => ['label' => 'Loại thanh toán', 'type' => 'select', 'options' => [0 => 'Đặt cọc', 1 => 'Thanh toán checkout']],
                'NgayThanhToan' => ['label' => 'Ngày thanh toán', 'type' => 'datetime-local'],
                'TrangThaiHoaDon' => ['label' => 'Trạng thái hóa đơn', 'type' => 'select', 'options' => [0 => 'Chưa thanh toán', 1 => 'Đã thanh toán']],
            ],
            'records' => [
                ['MaTT' => 1, 'MaHD' => 5001, 'SoTien' => 1500000, 'PhuongThuc' => 2, 'LoaiThanhToan' => 0, 'NgayThanhToan' => '2026-04-01T10:30', 'TrangThaiHoaDon' => 0],
                ['MaTT' => 2, 'MaHD' => 5002, 'SoTien' => 3250000, 'PhuongThuc' => 1, 'LoaiThanhToan' => 1, 'NgayThanhToan' => '2026-04-02T14:15', 'TrangThaiHoaDon' => 1],
            ],
        ],
        'reviews' => [
            'title' => 'Quản Lý Đánh Giá',
            'singular' => 'đánh giá',
            'description' => 'Theo dõi phản hồi sau lưu trú để cải thiện chất lượng dịch vụ.',
            'primary_key' => 'MaDG',
            'list_columns' => ['MaDG', 'MaDatPhong', 'Sao', 'MoTa', 'NgayDanhGia'],
            'fields' => [
                'MaDG' => ['label' => 'Mã đánh giá', 'type' => 'number', 'readonly' => true],
                'MaDatPhong' => ['label' => 'Mã đặt phòng', 'type' => 'number', 'required' => true],
                'Sao' => ['label' => 'Số sao', 'type' => 'select', 'options' => [1 => '1 sao', 2 => '2 sao', 3 => '3 sao', 4 => '4 sao', 5 => '5 sao']],
                'MoTa' => ['label' => 'Nội dung đánh giá', 'type' => 'textarea'],
                'NgayDanhGia' => ['label' => 'Ngày đánh giá', 'type' => 'date'],
            ],
            'records' => [
                ['MaDG' => 1, 'MaDatPhong' => 9001, 'Sao' => 5, 'MoTa' => 'Phòng sạch sẽ, nhân viên hỗ trợ nhiệt tình.', 'NgayDanhGia' => '2026-03-29'],
                ['MaDG' => 2, 'MaDatPhong' => 9002, 'Sao' => 4, 'MoTa' => 'Dịch vụ tốt, bữa sáng đa dạng.', 'NgayDanhGia' => '2026-03-31'],
                ['MaDG' => 3, 'MaDatPhong' => 9003, 'Sao' => 3, 'MoTa' => 'Cần cải thiện thời gian check-in.', 'NgayDanhGia' => '2026-04-01'],
            ],
        ],
    ],
    'reports' => [
        'title' => 'Báo Cáo Thống Kê',
        'summary_cards' => [
            ['label' => 'Khách hàng', 'value' => '128', 'description' => 'Khách hàng đang lưu trong hệ thống'],
            ['label' => 'Phòng đang sử dụng', 'value' => '42', 'description' => 'Số phòng hiện có khách lưu trú'],
            ['label' => 'Doanh thu hôm nay', 'value' => '32.500.000 VNĐ', 'description' => 'Tổng thanh toán phát sinh trong ngày'],
            ['label' => 'Đánh giá trung bình', 'value' => '4.6 / 5', 'description' => 'Tổng hợp từ phản hồi khách hàng'],
        ],
        'monthly_revenue' => [
            ['month' => 'Tháng 1', 'value' => 210000000],
            ['month' => 'Tháng 2', 'value' => 240000000],
            ['month' => 'Tháng 3', 'value' => 268000000],
            ['month' => 'Tháng 4', 'value' => 285000000],
        ],
        'room_status' => [
            ['label' => 'Trống', 'value' => 18],
            ['label' => 'Đã đặt', 'value' => 9],
            ['label' => 'Đang sử dụng', 'value' => 42],
            ['label' => 'Đang dọn dẹp', 'value' => 6],
        ],
    ],
];
