<?php

return [
    'modules' => [
        'customers' => [
            'title' => 'Quản Lý Khách Hàng',
            'singular' => 'khách hàng',
            'description' => 'Danh sách khách hàng đang lưu trữ trong hệ thống khách sạn.',
            'primary_key' => 'MaKH',
            'filters' => [
                'trang_thai' => [
                    'label' => 'Trạng thái',
                    'type' => 'select',
                    'field' => 'TrangThai',
                    'options' => [
                        '' => 'Tất cả trạng thái',
                        0 => 'Không hoạt động',
                        1 => 'Hoạt động',
                    ],
                ],
            ],
            'list_columns' => ['MaKH', 'MaTK', 'TenKH', 'DiaChi', 'SoDienThoai', 'CCCD', 'NgaySinh', 'GioiTinh', 'Diem', 'TrangThai'],
            'fields' => [
                'MaKH' => ['label' => 'Mã khách hàng', 'type' => 'number', 'readonly' => true],
                'MaTK' => ['label' => 'Mã tài khoản', 'type' => 'number', 'required' => true],
                'TenKH' => ['label' => 'Tên khách hàng', 'type' => 'text', 'required' => true],
                'DiaChi' => ['label' => 'Địa chỉ', 'type' => 'textarea', 'required' => true],
                'SoDienThoai' => ['label' => 'Số điện thoại', 'type' => 'text', 'required' => true],
                'CCCD' => ['label' => 'CCCD', 'type' => 'text', 'required' => true],
                'NgaySinh' => ['label' => 'Ngày sinh', 'type' => 'date', 'required' => true],
                'GioiTinh' => ['label' => 'Giới tính', 'type' => 'select', 'options' => [0 => 'Nữ', 1 => 'Nam', 2 => 'Khác']],
                'Diem' => ['label' => 'Điểm tích lũy', 'type' => 'number'],
                'TrangThai' => ['label' => 'Trạng thái', 'type' => 'select', 'options' => [0 => 'Không hoạt động', 1 => 'Hoạt động']],
            ],
            'records' => [
                ['MaKH' => 1, 'MaTK' => 101, 'TenKH' => 'Nguyễn Minh An', 'DiaChi' => '12 Nguyễn Huệ, Quận 1, TP.HCM', 'SoDienThoai' => '0901234567', 'CCCD' => '079204000111', 'NgaySinh' => '1998-04-12', 'GioiTinh' => 1, 'Diem' => 120, 'TrangThai' => 1],
                ['MaKH' => 2, 'MaTK' => 102, 'TenKH' => 'Trần Bảo Ngọc', 'DiaChi' => '55 Lê Lợi, Hải Châu, Đà Nẵng', 'SoDienThoai' => '0912345678', 'CCCD' => '048204000222', 'NgaySinh' => '2000-08-24', 'GioiTinh' => 0, 'Diem' => 80, 'TrangThai' => 1],
                ['MaKH' => 3, 'MaTK' => 103, 'TenKH' => 'Lê Quốc Huy', 'DiaChi' => '99 Hai Bà Trưng, Ninh Kiều, Cần Thơ', 'SoDienThoai' => '0987654321', 'CCCD' => '079204000333', 'NgaySinh' => '1995-11-03', 'GioiTinh' => 1, 'Diem' => 35, 'TrangThai' => 0],
            ],
        ],
        'accounts' => [
            'title' => 'Quản Lý Tài Khoản',
            'singular' => 'tài khoản',
            'description' => 'Quản lý thông tin đăng nhập, phân loại tài khoản và trạng thái sử dụng.',
            'primary_key' => 'MaTK',
            'list_columns' => ['MaTK', 'Email', 'LoaiTaiKhoan', 'TrangThai'],
            'fields' => [
                'MaTK' => ['label' => 'Mã tài khoản', 'type' => 'number', 'readonly' => true],
                'Email' => ['label' => 'Email', 'type' => 'email', 'required' => true],
                'MatKhau' => ['label' => 'Mật khẩu', 'type' => 'password', 'required' => true],
                'LoaiTaiKhoan' => ['label' => 'Loại tài khoản', 'type' => 'select', 'options' => [0 => 'Khách hàng', 1 => 'Lễ tân', 2 => 'Quản lý']],
                'TrangThai' => ['label' => 'Trạng thái', 'type' => 'select', 'options' => [0 => 'Không hoạt động', 1 => 'Hoạt động']],
            ],
            'records' => [
                ['MaTK' => 101, 'Email' => 'minhan@gmail.com', 'MatKhau' => '••••••••', 'LoaiTaiKhoan' => 0, 'TrangThai' => 1],
                ['MaTK' => 201, 'Email' => 'letan01@peachvalley.vn', 'MatKhau' => '••••••••', 'LoaiTaiKhoan' => 1, 'TrangThai' => 1],
                ['MaTK' => 301, 'Email' => 'admin@peachvalley.vn', 'MatKhau' => '••••••••', 'LoaiTaiKhoan' => 2, 'TrangThai' => 1],
            ],
        ],
        'employees' => [
            'title' => 'Quản Lý Nhân Viên',
            'singular' => 'nhân viên',
            'description' => 'Danh sách quản lý thông tin nhân viên.',
            'primary_key' => 'MaNV',
            'list_columns' => ['MaNV', 'TenNV', 'MaTK'],
            'fields' => [
                'MaNV' => ['label' => 'Mã nhân viên', 'type' => 'number', 'readonly' => true],
                'TenNV' => ['label' => 'Tên nhân viên', 'type' => 'text', 'required' => true],
                'MaTK' => ['label' => 'Mã tài khoản', 'type' => 'number', 'required' => true],
            ],
            'records' => [
                ['MaNV' => 1, 'TenNV' => 'Phạm Thùy Linh', 'MaTK' => 201],
                ['MaNV' => 2, 'TenNV' => 'Hoàng Gia Bảo', 'MaTK' => 202],
                ['MaNV' => 3, 'TenNV' => 'Đặng Tuấn Kiệt', 'MaTK' => 301],
            ],
        ],
        'room-types' => [
            'title' => 'Quản Lý Loại Phòng',
            'singular' => 'loại phòng',
            'description' => 'Danh sách quản lý thông tin loại phòng tại khách sạn.',
            'primary_key' => 'MaLoaiPhong',
            'list_columns' => ['MaLoaiPhong', 'TenLoaiPhong', 'Mota', 'SoNguoiToiDa'],
            'fields' => [
                'MaLoaiPhong' => ['label' => 'Mã loại phòng', 'type' => 'number', 'readonly' => true],
                'TenLoaiPhong' => ['label' => 'Tên loại phòng', 'type' => 'text', 'required' => true],
                'Mota' => ['label' => 'Mô tả', 'type' => 'textarea'],
                'SoNguoiToiDa' => ['label' => 'Số người tối đa', 'type' => 'number', 'required' => true],
            ],
            'records' => [
                ['MaLoaiPhong' => 1, 'TenLoaiPhong' => 'Deluxe', 'Mota' => 'Phòng tiêu chuẩn cao cấp, phù hợp cho khách đi công tác hoặc cặp đôi.', 'SoNguoiToiDa' => 2],
                ['MaLoaiPhong' => 2, 'TenLoaiPhong' => 'Suite', 'Mota' => 'Không gian rộng rãi, có khu vực tiếp khách riêng và tầm nhìn đẹp.', 'SoNguoiToiDa' => 4],
                ['MaLoaiPhong' => 3, 'TenLoaiPhong' => 'Family', 'Mota' => 'Thiết kế cho nhóm bạn hoặc gia đình nhỏ với sức chứa linh hoạt.', 'SoNguoiToiDa' => 5],
            ],
        ],
        'rooms' => [
            'title' => 'Quản Lý Phòng',
            'singular' => 'phòng',
            'description' => 'Danh sách quản lý thông tin các phòng tại khách sạn.',
            'primary_key' => 'MaPhong',
            'filters' => [
                'tinh_trang' => [
                    'label' => 'Tình trạng',
                    'type' => 'select',
                    'field' => 'TinhTrang',
                    'options' => [
                        '' => 'Tất cả tình trạng',
                        0 => 'Trống',
                        1 => 'Đã đặt',
                        2 => 'Đang sử dụng',
                        3 => 'Đang dọn dẹp',
                    ],
                ],
            ],
            'list_columns' => ['MaPhong', 'SoPhong', 'TenLoaiPhong', 'MaLoaiPhong', 'TinhTrang'],
            'fields' => [
                'MaPhong' => ['label' => 'Mã phòng', 'type' => 'number', 'readonly' => true],
                'SoPhong' => ['label' => 'Số phòng', 'type' => 'text', 'required' => true],
                'MaLoaiPhong' => ['label' => 'Mã loại phòng', 'type' => 'number', 'required' => true],
                'TenLoaiPhong' => ['label' => 'Tên loại phòng', 'type' => 'text'],
                'TinhTrang' => ['label' => 'Tình trạng', 'type' => 'select', 'options' => [0 => 'Trống', 1 => 'Đã đặt', 2 => 'Đang sử dụng', 3 => 'Đang dọn dẹp']],
            ],
            'records' => [
                ['MaPhong' => 1, 'SoPhong' => 'A101', 'MaLoaiPhong' => 1, 'TenLoaiPhong' => 'Deluxe', 'TinhTrang' => 0],
                ['MaPhong' => 2, 'SoPhong' => 'A102', 'MaLoaiPhong' => 2, 'TenLoaiPhong' => 'Suite', 'TinhTrang' => 2],
                ['MaPhong' => 3, 'SoPhong' => 'B201', 'MaLoaiPhong' => 1, 'TenLoaiPhong' => 'Deluxe', 'TinhTrang' => 3],
            ],
        ],
        'services' => [
            'title' => 'Quản Lý Dịch Vụ',
            'singular' => 'dịch vụ',
            'description' => 'Danh sách dịch vụ khách sạn theo nhóm ăn uống, phòng và giải trí.',
            'primary_key' => 'MaDV',
            'list_columns' => ['MaDV', 'TenDV', 'GiaDV', 'LoaiDV'],
            'fields' => [
                'MaDV' => ['label' => 'Mã dịch vụ', 'type' => 'number', 'readonly' => true],
                'TenDV' => ['label' => 'Tên dịch vụ', 'type' => 'text', 'required' => true],
                'GiaDV' => ['label' => 'Giá dịch vụ', 'type' => 'number', 'step' => '0.01', 'required' => true],
                'LoaiDV' => ['label' => 'Loại dịch vụ', 'type' => 'select', 'options' => [0 => 'Dịch vụ ăn uống', 1 => 'Dịch vụ phòng', 2 => 'Dịch vụ giải trí']],
            ],
            'records' => [
                ['MaDV' => 1, 'TenDV' => 'Bánh mì', 'GiaDV' => 35000, 'LoaiDV' => 0],
                ['MaDV' => 2, 'TenDV' => 'Cơm chiên', 'GiaDV' => 60000, 'LoaiDV' => 0],
                ['MaDV' => 3, 'TenDV' => 'Bún bò', 'GiaDV' => 55000, 'LoaiDV' => 0],
                ['MaDV' => 4, 'TenDV' => 'Bún thái', 'GiaDV' => 65000, 'LoaiDV' => 0],
                ['MaDV' => 5, 'TenDV' => 'Cà phê sữa', 'GiaDV' => 30000, 'LoaiDV' => 0],
                ['MaDV' => 6, 'TenDV' => 'Giặt ủi', 'GiaDV' => 120000, 'LoaiDV' => 1],
                ['MaDV' => 7, 'TenDV' => 'Vệ sinh', 'GiaDV' => 90000, 'LoaiDV' => 1],
                ['MaDV' => 8, 'TenDV' => 'Đổi phòng', 'GiaDV' => 150000, 'LoaiDV' => 1],
                ['MaDV' => 9, 'TenDV' => 'Hủy phòng', 'GiaDV' => 300000, 'LoaiDV' => 1],
                ['MaDV' => 10, 'TenDV' => 'Thêm giường phụ', 'GiaDV' => 220000, 'LoaiDV' => 1],
                ['MaDV' => 11, 'TenDV' => 'Spa', 'GiaDV' => 850000, 'LoaiDV' => 2],
                ['MaDV' => 12, 'TenDV' => 'Cưỡi ngựa', 'GiaDV' => 650000, 'LoaiDV' => 2],
                ['MaDV' => 13, 'TenDV' => 'Golf', 'GiaDV' => 1250000, 'LoaiDV' => 2],
            ],
        ],
        'promotions' => [
            'title' => 'Quản Lý Khuyến Mãi',
            'singular' => 'khuyến mãi',
            'description' => 'Danh sách quản lý theo dõi chương trình ưu đãi từ khách sạn.',
            'primary_key' => 'MaKM',
            'list_columns' => ['MaKM', 'TenKM', 'Diem', 'NgayBatDau', 'NgayKetThuc', 'PhanTramGiamGia'],
            'fields' => [
                'MaKM' => ['label' => 'Mã khuyến mãi', 'type' => 'number', 'readonly' => true],
                'TenKM' => ['label' => 'Tên chương trình', 'type' => 'text', 'required' => true],
                'MoTa' => ['label' => 'Mô tả', 'type' => 'textarea', 'required' => true],
                'Diem' => ['label' => 'Điểm yêu cầu', 'type' => 'number'],
                'NgayBatDau' => ['label' => 'Ngày bắt đầu', 'type' => 'date', 'required' => true],
                'NgayKetThuc' => ['label' => 'Ngày kết thúc', 'type' => 'date', 'required' => true],
                'PhanTramGiamGia' => ['label' => 'Phần trăm giảm giá', 'type' => 'number', 'step' => '0.01', 'required' => true],
            ],
            'records' => [
                ['MaKM' => 1, 'TenKM' => 'Summer Escape', 'MoTa' => 'Giảm giá cho khách đặt phòng trong mùa hè.', 'Diem' => 50, 'NgayBatDau' => '2026-05-01', 'NgayKetThuc' => '2026-06-30', 'PhanTramGiamGia' => 15],
                ['MaKM' => 2, 'TenKM' => 'Stay Longer', 'MoTa' => 'Ưu đãi dành cho khách ở từ 3 đêm trở lên.', 'Diem' => 80, 'NgayBatDau' => '2026-04-15', 'NgayKetThuc' => '2026-07-31', 'PhanTramGiamGia' => 20],
            ],
        ],
        'invoices' => [
            'title' => 'Quản Lý Hóa Đơn',
            'singular' => 'hóa đơn',
            'description' => 'Danh sách quản lý thông tin hóa đơn tại khách sạn.',
            'primary_key' => 'MaHD',
            'allow_create' => false,
            'allow_edit' => false,
            'allow_delete' => false,
            'filters' => [
                'trang_thai' => [
                    'label' => 'Trạng thái',
                    'type' => 'select',
                    'field' => 'TrangThai',
                    'options' => [
                        '' => 'Tất cả trạng thái',
                        0 => 'Chưa thanh toán',
                        1 => 'Đã thanh toán',
                    ],
                ],
            ],
            'list_columns' => ['MaHD', 'MaDatPhong', 'NgayLapHD', 'MaNV', 'TenNV', 'TongTien', 'DaThanhToan', 'TrangThai'],
            'fields' => [
                'MaHD' => ['label' => 'Mã hóa đơn', 'type' => 'number', 'readonly' => true],
                'MaDatPhong' => ['label' => 'Mã đặt phòng', 'type' => 'number', 'readonly' => true],
                'NgayLapHD' => ['label' => 'Ngày lập hóa đơn', 'type' => 'date', 'readonly' => true],
                'MaKM' => ['label' => 'Mã khuyến mãi', 'type' => 'number', 'readonly' => true],
                'TongTien' => ['label' => 'Tổng tiền', 'type' => 'number', 'readonly' => true],
                'MaNV' => ['label' => 'Mã nhân viên', 'type' => 'number', 'readonly' => true],
                'TenNV' => ['label' => 'Họ tên nhân viên', 'type' => 'text', 'readonly' => true],
                'TrangThai' => ['label' => 'Trạng thái', 'type' => 'select', 'options' => [0 => 'Chưa thanh toán', 1 => 'Đã thanh toán'], 'readonly' => true],
                'DaThanhToan' => ['label' => 'Đã thanh toán', 'type' => 'number', 'readonly' => true],
            ],
            'records' => [
                ['MaHD' => 5001, 'MaDatPhong' => 9001, 'NgayLapHD' => '2026-04-01', 'MaKM' => 2, 'TongTien' => 4500000, 'MaNV' => 1, 'TrangThai' => 0, 'DaThanhToan' => 1500000],
                ['MaHD' => 5002, 'MaDatPhong' => 9002, 'NgayLapHD' => '2026-04-02', 'MaKM' => null, 'TongTien' => 3250000, 'MaNV' => 2, 'TrangThai' => 1, 'DaThanhToan' => 3250000],
                ['MaHD' => 5003, 'MaDatPhong' => 9003, 'NgayLapHD' => '2026-04-04', 'MaKM' => 1, 'TongTien' => 5900000, 'MaNV' => 1, 'TrangThai' => 0, 'DaThanhToan' => 2000000],
            ],
        ],
        'payments' => [
            'title' => 'Quản Lý Thanh Toán',
            'singular' => 'thanh toán',
            'description' => 'Quản lý thông tin thanh toán, hóa đơn.',
            'primary_key' => 'MaTT',
            'list_columns' => ['MaTT', 'MaHD', 'SoTien', 'PhuongThuc', 'LoaiThanhToan', 'NgayThanhToan', 'TrangThaiHoaDon'],
            'fields' => [
                'MaTT' => ['label' => 'Mã thanh toán', 'type' => 'number', 'readonly' => true],
                'MaHD' => ['label' => 'Mã hóa đơn', 'type' => 'number', 'required' => true],
                'SoTien' => ['label' => 'Số tiền', 'type' => 'number', 'step' => '0.01', 'required' => true],
                'PhuongThuc' => ['label' => 'Phương thức', 'type' => 'select', 'options' => [1 => 'Thẻ', 2 => 'QRCode']],
                'LoaiThanhToan' => ['label' => 'Loại thanh toán', 'type' => 'select', 'options' => [0 => 'Đặt cọc', 1 => 'Thanh toán checkout']],
                'NgayThanhToan' => ['label' => 'Ngày thanh toán', 'type' => 'datetime-local'],
                'TrangThaiHoaDon' => ['label' => 'Trạng thái hóa đơn', 'type' => 'select', 'options' => [0 => 'Chưa thanh toán', 1 => 'Đã thanh toán']],
            ],
            'records' => [
                ['MaTT' => 1, 'MaHD' => 5001, 'SoTien' => 1500000, 'PhuongThuc' => 2, 'LoaiThanhToan' => 0, 'NgayThanhToan' => '2026-04-01T10:30', 'TrangThaiHoaDon' => 0],
                ['MaTT' => 2, 'MaHD' => 5002, 'SoTien' => 3250000, 'PhuongThuc' => 1, 'LoaiThanhToan' => 1, 'NgayThanhToan' => '2026-04-02T14:15', 'TrangThaiHoaDon' => 1],
            ],
        ],
        'reviews' => [
            'title' => 'Quản Lý Đánh Giá',
            'singular' => 'đánh giá',
            'description' => 'Theo dõi phản hồi sau lưu trú để cải thiện chất lượng dịch vụ.',
            'primary_key' => 'MaDG',
            'allow_create' => false,
            'allow_edit' => false,
            'allow_delete' => false,
            'filters' => [
                'ngay_danh_gia_tu' => [
                    'label' => 'Từ ngày',
                    'type' => 'date',
                    'field' => 'NgayDanhGia',
                    'operator' => '>=',
                ],
                'ngay_danh_gia_den' => [
                    'label' => 'Đến ngày',
                    'type' => 'date',
                    'field' => 'NgayDanhGia',
                    'operator' => '<=',
                ],
                'sao' => [
                    'label' => 'Số sao',
                    'type' => 'select',
                    'field' => 'Sao',
                    'options' => [
                        '' => 'Tất cả số sao',
                        5 => '5 sao',
                        4 => '4 sao',
                        3 => '3 sao',
                        2 => '2 sao',
                        1 => '1 sao',
                    ],
                ],
            ],
            'list_columns' => ['MaDG', 'MaDatPhong', 'Sao', 'MoTa', 'NgayDanhGia'],
            'fields' => [
                'MaDG' => ['label' => 'Mã đánh giá', 'type' => 'number', 'readonly' => true],
                'MaDatPhong' => ['label' => 'Mã đặt phòng', 'type' => 'number', 'required' => true],
                'Sao' => ['label' => 'Số sao', 'type' => 'select', 'options' => [1 => '1 sao', 2 => '2 sao', 3 => '3 sao', 4 => '4 sao', 5 => '5 sao']],
                'MoTa' => ['label' => 'Nội dung đánh giá', 'type' => 'textarea'],
                'NgayDanhGia' => ['label' => 'Ngày đánh giá', 'type' => 'date'],
            ],
            'records' => [
                ['MaDG' => 1, 'MaDatPhong' => 9001, 'Sao' => 5, 'MoTa' => 'Phòng sạch sẽ, nhân viên hỗ trợ nhiệt tình.', 'NgayDanhGia' => '2026-03-29'],
                ['MaDG' => 2, 'MaDatPhong' => 9002, 'Sao' => 4, 'MoTa' => 'Dịch vụ tốt, bữa sáng đa dạng.', 'NgayDanhGia' => '2026-03-31'],
                ['MaDG' => 3, 'MaDatPhong' => 9003, 'Sao' => 3, 'MoTa' => 'Cần cải thiện thời gian check-in.', 'NgayDanhGia' => '2026-04-01'],
            ],
        ],
    ],
    'reports' => [
        'title' => 'Báo Cáo Thống Kê',
        'summary_cards' => [
            ['label' => 'Khách hàng', 'value' => '128', 'description' => 'Khách hàng đang lưu trong hệ thống', 'icon' => 'customers', 'icon_class' => 'text-primary'],
            ['label' => 'Phòng đang sử dụng', 'value' => '42', 'description' => 'Số phòng hiện có khách lưu trú', 'icon' => 'rooms', 'icon_class' => 'text-success'],
            ['label' => 'Doanh thu hôm nay', 'value' => '32.500.000 VNĐ', 'description' => 'Tổng thanh toán phát sinh trong ngày', 'icon' => 'revenue', 'icon_class' => 'revenue-icon-blue'],
            ['label' => 'Đánh giá trung bình', 'value' => '4.6 / 5', 'description' => 'Tổng hợp từ phản hồi khách hàng', 'icon' => 'reviews', 'icon_class' => 'text-warning'],
        ],
        'monthly_revenue' => [
            ['month' => 'Tháng 1', 'value' => 210000000],
            ['month' => 'Tháng 2', 'value' => 240000000],
            ['month' => 'Tháng 3', 'value' => 268000000],
            ['month' => 'Tháng 4', 'value' => 285000000],
        ],
        'revenue_chart' => [
            'default_period' => 'month',
            'periods' => [
                'day' => [
                    'label' => 'Theo ngày',
                    'title' => 'Doanh thu theo ngày',
                    'items' => [
                        ['key' => '2026-04-01', 'label' => '01/04', 'value' => 8500000],
                        ['key' => '2026-04-02', 'label' => '02/04', 'value' => 9200000],
                        ['key' => '2026-04-03', 'label' => '03/04', 'value' => 8700000],
                        ['key' => '2026-04-04', 'label' => '04/04', 'value' => 11000000],
                        ['key' => '2026-04-05', 'label' => '05/04', 'value' => 9800000],
                        ['key' => '2026-04-06', 'label' => '06/04', 'value' => 12400000],
                        ['key' => '2026-04-07', 'label' => '07/04', 'value' => 13200000],
                        ['key' => '2026-04-08', 'label' => '08/04', 'value' => 12800000],
                        ['key' => '2026-04-09', 'label' => '09/04', 'value' => 13600000],
                        ['key' => '2026-04-10', 'label' => '10/04', 'value' => 14200000],
                    ],
                ],
                'month' => [
                    'label' => 'Theo tháng',
                    'title' => 'Doanh thu theo tháng',
                    'items' => [
                        ['key' => '2025-11', 'label' => 'Tháng 11', 'value' => 198000000],
                        ['key' => '2025-12', 'label' => 'Tháng 12', 'value' => 205000000],
                        ['key' => '2026-01', 'label' => 'Tháng 1', 'value' => 210000000],
                        ['key' => '2026-02', 'label' => 'Tháng 2', 'value' => 240000000],
                        ['key' => '2026-03', 'label' => 'Tháng 3', 'value' => 268000000],
                        ['key' => '2026-04', 'label' => 'Tháng 4', 'value' => 285000000],
                        ['key' => '2026-05', 'label' => 'Tháng 5', 'value' => 301000000],
                        ['key' => '2026-06', 'label' => 'Tháng 6', 'value' => 318000000],
                    ],
                ],
                'year' => [
                    'label' => 'Theo năm',
                    'title' => 'Doanh thu theo năm',
                    'items' => [
                        ['key' => '2022', 'label' => '2022', 'value' => 1960000000],
                        ['key' => '2023', 'label' => '2023', 'value' => 2200000000],
                        ['key' => '2024', 'label' => '2024', 'value' => 2540000000],
                        ['key' => '2025', 'label' => '2025', 'value' => 2890000000],
                        ['key' => '2026', 'label' => '2026', 'value' => 3175000000],
                    ],
                ],
            ],
        ],
        'room_status' => [
            ['label' => 'Trống', 'value' => 18],
            ['label' => 'Đã đặt', 'value' => 9],
            ['label' => 'Đang sử dụng', 'value' => 42],
            ['label' => 'Đang dọn dẹp', 'value' => 6],
        ],
    ],
    'demo_auth' => [
        'password' => '123456',
        'users' => [
            [
                'email' => 'minhan@gmail.com',
                'password' => '123456',
                'name' => 'Nguyễn Minh An',
                'role' => 'customer',
                'role_label' => 'Khách hàng',
                'status' => 1,
            ],
            [
                'email' => 'admin@peachvalley.vn',
                'password' => '123456',
                'name' => 'Nguyễn Hải Đăng',
                'role' => 'manager',
                'role_label' => 'Quản lý',
                'status' => 1,
            ],
            [
                'email' => 'letan01@peachvalley.vn',
                'password' => '123456',
                'name' => 'Phạm Thùy Linh',
                'role' => 'receptionist',
                'role_label' => 'Lễ tân',
                'status' => 1,
            ],
        ],
    ],
    'reception' => [
        'brand' => [
            'title' => 'Peach Valley Front Desk',
            'subtitle' => 'Khu làm việc dành cho lễ tân, tối ưu cho check-in, đặt phòng và theo dõi hóa đơn trong ngày.',
        ],
        'bookings' => [
            'records' => [
                [
                    'MaDatPhong' => 9001,
                    'MaKH' => 1,
                    'TenKH' => 'Nguyễn Minh An',
                    'SoDienThoai' => '0901234567',
                    'SoPhong' => 'A101',
                    'LoaiPhong' => 'Deluxe',
                    'NgayDat' => '2026-04-05',
                    'NgayNhanPhong' => '2026-04-08',
                    'NgayTraPhong' => '2026-04-10',
                    'SoLuong' => 2,
                    'TinhTrang' => 0,
                ],
                [
                    'MaDatPhong' => 9002,
                    'MaKH' => 2,
                    'TenKH' => 'Trần Bảo Ngọc',
                    'SoDienThoai' => '0912345678',
                    'SoPhong' => 'A102',
                    'LoaiPhong' => 'Suite',
                    'NgayDat' => '2026-04-04',
                    'NgayNhanPhong' => '2026-04-07',
                    'NgayTraPhong' => '2026-04-09',
                    'SoLuong' => 2,
                    'TinhTrang' => 1,
                ],
                [
                    'MaDatPhong' => 9003,
                    'MaKH' => 3,
                    'TenKH' => 'Lê Quốc Huy',
                    'SoDienThoai' => '0987654321',
                    'SoPhong' => 'B201',
                    'LoaiPhong' => 'Deluxe',
                    'NgayDat' => '2026-04-06',
                    'NgayNhanPhong' => '2026-04-09',
                    'NgayTraPhong' => '2026-04-12',
                    'SoLuong' => 1,
                    'TinhTrang' => 2,
                ],
                [
                    'MaDatPhong' => 9004,
                    'MaKH' => 4,
                    'TenKH' => 'Phạm Khánh Vy',
                    'SoDienThoai' => '0934556677',
                    'SoPhong' => 'C301',
                    'LoaiPhong' => 'Family',
                    'NgayDat' => '2026-04-03',
                    'NgayNhanPhong' => '2026-04-08',
                    'NgayTraPhong' => '2026-04-11',
                    'SoLuong' => 4,
                    'TinhTrang' => 0,
                ],
                [
                    'MaDatPhong' => 9005,
                    'MaKH' => 5,
                    'TenKH' => 'Đỗ Thanh Tùng',
                    'SoDienThoai' => '0978112233',
                    'SoPhong' => 'B202',
                    'LoaiPhong' => 'Suite',
                    'NgayDat' => '2026-04-02',
                    'NgayNhanPhong' => '2026-04-06',
                    'NgayTraPhong' => '2026-04-08',
                    'SoLuong' => 2,
                    'TinhTrang' => 3,
                ],
            ],
        ],
    ],
];
